#include <iostream>
#include <fstream>
#include <string>

using namespace std;

enum OPCIONES
{
    AGREGAR = 1,
    EDITAR,
    LEER,
    LISTAR
};
enum OPCIONESCANCIO
{
    VERSO,
    PREETRIBILLO,
    ESTRIBILLO,
    PUENTE,
    ATRAS
};

void escribir(string nombre, int opcion)
{
}

int menu()
{

    int op;

    cout << "<-------------------------->" << "\n   SONG CREATOR HELPER      "
}

int main(void)
{

    int opcion;
    opcion = menu();
    return 0;
}